fix: added missing translations
saas-js/saas-ui pull request #207
Opened 2024-02-20 11:31 UTC by kalpesh3000

Added missing translations for the update-password.

2024-02-20 11:56 UTC, Pagebakers requested changes
Perfect, can you update the changeset to be a patch instead of major then i can merge it in and release it.

2024-02-20 11:56 UTC, Pagebakers commented on .changeset/good-penguins-collect.md
> +"website": major
This should be a patch change

2024-02-20 11:56 UTC, Pagebakers commented on .changeset/good-penguins-collect.md
> +"@saas-ui/auth": major
Should be `patch`

2024-02-21 04:13 UTC, kalpesh3000 commented on .changeset/good-penguins-collect.md
> +"website": major
Done.

2024-02-21 04:13 UTC, kalpesh3000 commented on .changeset/good-penguins-collect.md
> +"@saas-ui/auth": major
Done.

2024-02-21 12:06 UTC, Pagebakers approved these changes

2024-02-21 12:06 UTC, merged